- name: base packages
  yum: name='{{ item }}' state=present
  with_items:
         - git
         - mariadb
         - mariadb-server
         - httpd
         - MySQL-python

- name: upgrade php
  shell: amazon-linux-extras install '{{ item }}' state=present
  with_items:
         - php7.2
         - php7.2-curl
         - php7.2-gd
         - php7.2-cli
         - php7.2-mysql
         - php7.2-xml
         - php7.2-mbstring
         - php7.2-fpm
         - php7.2-json
         - php7.2-intl
         - php7.2-zip


#- name: pip packages
#  pip: 
#    name: flask
#- name: pip packages
#  pip: 
#    name: flask-wtf
