- name: base packages
  yum: name='{{ item }}' state=present
  with_items:
         - git
         - php
         - mariadb
         - mariadb-server
         - httpd
         - MySQL-python
         - php-curl
         - php-gd
         - php-cli
         - php-mysql
         - php-xml
         - php-mbstring
         - php-fpm
         - php-json
         - php-intl
         - php-zip

#- name: pip packages
#  pip: 
#    name: flask
#- name: pip packages
#  pip: 
#    name: flask-wtf
