- name: base packages
  yum: name='{{ item }}' state=present
  with_items:
         - git
         - php
         - mariadb
         - mariadb-server
         - httpd

#- name: pip packages
#  pip: 
#    name: flask
#- name: pip packages
#  pip: 
#    name: flask-wtf
