- name: install composer.phar script
  copy:
    src: usr/sbin/composer.phar
    dest: /usr/sbin/composer.phar
    mode: '0755'

- name: start httpd
  service:
    name: httpd
    state: started

- name: start mariadb
  service:
    name: mariadb
    state: started

- name: create my.cnf for root user
  template:
    src: root/.my.cnf
    dest: /root/.my.cnf
    mode: 0600

- name: set root credentials for mariadb 
  mysql_user: name=root host=localhost password={{ mysql_root_pass }}

- name: create database for drupal
  mysql_db: name=drupal state=present

- name: create user for drupal
  mysql_user: name=drupal  password={{ drupal_pass }} priv="drupal.*:ALL" state=present 
