- name: install composer.phar script
  copy:
    src: usr/sbin/composer.phar
    dest: /usr/sbin/composer.phar
    mode: '0755'

- name: start httpd
  service:
    name: httpd
    state: started

- name: start mariadb
  service:
    name: mariadb
    state: started

- name: create my.cnf for root user
  template:
    src: root/.my.cnf
    dest: /root/.my.cnf
    mode: 0600

- name: set root credentials for mariadb 
  mysql_user: name=root host=localhost password={{ mysql_root_pass }}

- name: create database for drupal
  mysql_db: name=drupal state=present

- name: create user for drupal
  mysql_user: name=drupal  password={{ drupal_pass }} priv="drupal.*:ALL" state=present 

- name: get drush repository
  git:
    repo: https://github.com/drush-ops/drush.git
    version: "9.7.1"
    dest: /opt/drush

- name: install drush 
  shell: composer.phar install
  args:
    chdir: "/opt/drush"

- name: link drush binary
  file:
    src: /opt/drush/drush
    dest: /usr/sbin/drush
    state: link

- name: create drupal dir
  file:
    path: "/var/www/html/blog"
    state: directory

- name: clone drupal git
  git:
    repo: http://git.drupal.org/project/drupal.git
    version: "8.7.8"
    dest: "/var/www/html/blog"

- name: install drupal
  shell: composer.phar install
  args:
    chdir: "/var/www/html/blog"
    creates: "/var/www/html/blog/vendor/autoload.php"

- name: setup drupal
  shell: drush si -y --site-name='Blog' --account-name='admin' --account-pass='{{ drupal_admin_pass }}' --db-url='mysql://drupal:{{ drupal_pass }}@localhost/drupal'
  args:
    chdir: "/var/www/html/blog"

- name: fix ownership
  file:
    path: "/var/www/html/blog"
    owner: apache
    group: apache
    recurse: yes

- name: set permissions on the settings file
  file:
    path: "/var/www/html/blog/sites/default/settings.php"
    mode: 0744

- name: set permissions on files direcotry
  file:
    path: "/var/www/html/blog/sites/default/files"
    mode: 0777
    state: directory
    recurse: yes
 
- name: copy httpd conf file
  copy:
    src: "etc/httpd/conf/httpd.conf"
    dest: "/etc/httpd/conf/httpd.conf"
    mode: '0755'

- name: copy drupal admin password
  copy:
    content: "{{ drual_admin_pass }}"
    dest: "/root/.drupal_admin_pass"
    mode: '0400'
