---

# Install EPEL so we can get certbot

- name:  EPEL configured?
  stat:
    path: "/etc/yum.repos.d/epel.repo"
  register: epel_status

- name: install EPEL 
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present
  when: not epel_status.stat.exists

- name: install certbot
  yum:
    name: "python2-certbot-apache.noarch"
    state: present

- name: certbot renew cron 
  copy:
    src: "etc/cron.d/certbot"
    dest: "/etc/cron.d/certbot"
    mode: '0644'
